# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 025fda0af3b933674b2732cf4afdce8323a9aa282e7df9835e1efffd58a61b4304bc341a856c275e4acf2f19e0216999f7e375b82f12456d5a65679fc2b1ec00

test:
  secret_key_base: e3a1fcd8ca1d5270e89f69a22826fcebc14e53efcd4e42e7052fe00c7ca5f1400c8b1178b4627b803e38c98b379659cc8446962290204f53fc41a17b8a9d5452

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
